version: "3.7"

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=rocketseat
    volumes:
     - pgdata/data/postgres
  app:
    build: .
    container_name: rocketseat
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    links:
      - database
    depends_on:
      - database
  

volumes:
  pgdata:
    driver: local